Iniciando o código
Developer-Academy-Mackenzie-2021-2022/NC4 pull request #7
Opened 2021-10-29 20:03 UTC by mviniss

Fazendo o começo do gráfico

### Motivação

### Alterações

### Resultado

2021-10-29 20:07 UTC, VitorGK requested changes
Renomear struct da View para "CashFlowChartView" e o da PreviewProvider para "CashFlowChartView_Previews"

2021-10-29 20:15 UTC, VitorGK approved these changes

2021-10-29 21:00 UTC, mviniss reviewed
Aprovando as mudanças

2021-11-04 16:59 UTC, ThaisBras approved these changes

2021-11-04 16:59 UTC, merged